name: gibas
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+7

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cached_network_image: ^3.3.1
  camera: 0.10.0+4
  cupertino_icons: ^1.0.0
  dio: ^5.8.0+1
  device_info_plus: ^11.5.0
  fl_chart: ^1.0.0
  flutter_dotenv: ^5.1.0
  flutter_image_compress: ^2.4.0
  flutter_map: ^8.0.0
  flutter_svg: ^2.1.0
  geocoding: ^4.0.0
  geolocator: ^14.0.0
  get_storage: ^2.0.3
  get: ^4.6.5
  google_fonts: ^6.2.1
  hive: ^2.2.3
  image_picker: ^1.1.2
  image: ^4.5.4
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.20.2
  latlong2: ^0.9.0
  package_info_plus: ^8.1.0
  path_provider: ^2.1.1
  permission_handler: ^12.0.0+1
  pretty_dio_logger: ^1.4.0
  sentry_flutter: ^9.1.0
  shimmer: ^3.0.0
  url_launcher: ^6.1.9
  google_mlkit_text_recognition: ^0.15.0
  flutter_exif_rotation: ^0.5.2
  iconsax: ^0.0.8
  pretty_qr_code: ^3.5.0
  flutter_html: ^3.0.0
  flutter_widget_from_html: ^0.17.1
  onesignal_flutter: ^5.3.4
  syncfusion_flutter_pdfviewer: ^31.1.19
  share_plus: ^11.0.0
  flutter_downloader: ^1.12.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  smooth_page_indicator: ^1.2.1
  google_mobile_ads: ^6.0.0
  flutter_nfc_kit: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon_driver.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icons/icon_driver.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
   - assets/icons/
   - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
